name: "🛰️Comunicador"

on:
  workflow_dispatch:
    inputs:
      villano:
        description: "¿Qué villano envía el mensaje?"
        required: true
        type: choice
        options:
          - "Lex Luthor"
          - "Magneto"
          - "Mystic"
          - "brainiac"
          - "Doomsday"
      mensaje:
        description: "Escribe el mensaje que deseas enviar."
        required: true
        default: "todo bien 😎"
      prioridad:
        description: "¿Cuál es la prioridad del mensaje?"
        required: true
        type: choice
        options:
          - "🟢 Alta"
          - "🟡 Media"
          - "🔴 Baja"

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir inputs
        run: |
          echo "Villano: ${{ github.event.inputs.villano }}"
          echo "Mensaje: ${{ github.event.inputs.mensaje }}"
          echo "Prioridad: ${{ github.event.inputs.prioridad }}"
