name: "🛰️Comunicador"

on:
  workflow_dispatch:
    inputs:
      villano:
        description: "¿Qué villano envía el mensaje?"
        required: true
        type: choice
        options:
          - "Lex Luthor"
          - "Magneto"
          - "Mystic"
          - "brainiac"
          - "Doomsday"
      mensaje:
        description: "Escribe el mensaje que deseas enviar."
        required: true
        default: "todo bien 😎"

      cow_character:
        description: "Elige el personaje de la vaca para el mensaje."
        required: true
        type: choice
        options:
          - "eyes"
          - "tux"
          - "dragon"
          - "ghostbusters"
      prioridad:
        description: "¿Cuál es la prioridad del mensaje?"
        required: true
        type: choice
        options:
          - "🟢 Alta"
          - "🟡 Media"
          - "🔴 Baja"

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar transmisor de la legión
        run: |
          echo "Instalando transmisor..."
          sudo apt-get install -y cowsay
      - name: "Imprimir inputs"
        run: |
          echo "============================="
          echo " transmisión interceptada"
          echo "Villano: ${{ github.event.inputs.villano }}"
          echo "Prioridad: ${{ github.event.inputs.prioridad }}"
          echo "Mensaje: ${{ github.event.inputs.mensaje }}"
          echo "Fecha: $(date -u + %d-%m-%Y %H:%M:%S UTC)"
          echo "============================="
          cowsay -f "${{ github.event.inputs.cow_character }}" "Villano: ${{ github.event.inputs.villano }} | Prioridad: ${{ github.event.inputs.prioridad }} | Mensaje: ${{ github.event.inputs.mensaje }}"
